# Generated by Django 6.0.7 on 2026-07-23 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_food', models.BooleanField()),
                ('confidence_score', models.FloatField()),
                ('top_label', models.CharField(max_length=100)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_verification', to='donations.fooddonation')),
            ],
        ),
    ]
